version: '3.7'

services:
  db:
    container_name: db_postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: api
    expose:
      - '5433'
    ports:
      - '5434:5434'
    command: -p 5434

  redis:
    container_name: redis_boilerplate
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    restart: always